# Core Variables
app-name                  = "oag-prod"
environment_tag           = "Dev/Test"
region1                   = "eastus2"
region2                   = "eastus"
subscription_id_hub       = "4dfb599e-8459-4600-86a9-a19faa01ad6d"
app_id                    = ""
tennant                   = ""
app_secret                = ""